In [1]:
import numpy as np
from sympy import exp, symbols, expand, collect

__1.__ Исследовать на линейную зависимость:

$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

__Решение__

Система векторов $\bar{\upsilon }_1,\text{...},\bar{\upsilon }_n$ называется линейно зависимой, если нулевой вектор раскладывается по ней не единственным образом,  то есть если найдутся такие коэффициенты, что $\alpha _1 \bar{\upsilon }_1+\text{...}+\bar{\upsilon }_1 \alpha _n=\bar {0}; \: \alpha ^2{}_1+\text{...}+\alpha ^2{}_n\neq 0$, но не все они равны нулю


In [2]:
x, alpha1, alpha2, alpha3, alpha4, alpha4_new = symbols(
    "x alpha1 alpha2 alpha3 alpha4 alpha4_new"
)

f1 = exp(x)
f2 = 1
f3 = x + 1
f4 = x - exp(x)

eq = expand(alpha1 * f1 + alpha2 * f2 + alpha3 * f3 + alpha4 * f4)
eq = collect(eq, [exp(x), x])
print(eq)

alpha2 + alpha3 + x*(alpha3 + alpha4) + (alpha1 - alpha4)*exp(x)


Если предположить, что векторы линейно независимы, можно сделать вывод, что все коэффициенты должны равняться нулю.

$\begin{cases}
 \alpha_{2} + \alpha_{3}=0,\\
 \alpha_{1} - \alpha_{4}=0,\\
 \alpha_{3} + \alpha_{4}=0
\end{cases}$

Сделаем замены

In [3]:
eq = expand(eq.subs({alpha1: alpha4_new, alpha2: alpha4_new, alpha3: -alpha4_new}))

print(collect(eq, [alpha4, alpha4_new]))

alpha4*(x - exp(x)) + alpha4_new*(-x + exp(x))


Векторы линейно зависимы

Заметим, что $f_{1}(x)=f_{3}(x) - f_{2}(x) - f_{4}(x)$, то есть вектор $f_{1}(x)$ — линейная комбинация векторов $f_{2}(x)$, $f_{3}(x)$ и $f_{4}(x)$, из чего можно сделать вывод, что векторы линейно зависимы.

__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$

__Решение__

In [4]:
f1 = 2
f2 = x
f3 = x**2
f4 = (x + 1) ** 2

eq = expand(alpha1 * f1 + alpha2 * f2 + alpha3 * f3 + alpha4 * f4)
eq = collect(eq, [exp(x), x])
print(eq)

2*alpha1 + alpha4 + x**2*(alpha3 + alpha4) + x*(alpha2 + 2*alpha4)


$\begin{cases}
 2 \alpha_{1} + \alpha_{4}=0,\\
 \alpha_{3} + \alpha_{4}=0,\\
 \alpha_{2} + 2 \alpha_{4}=0
\end{cases}$

Сделаем замены

In [5]:
eq = expand(
    eq.subs({alpha1: -alpha4_new / 2, alpha2: -2 * alpha4_new, alpha3: -alpha4_new})
)

print(collect(eq, [alpha4, alpha4_new]))

alpha4*(x**2 + 2*x + 1) + alpha4_new*(-x**2 - 2*x - 1)


Векторы линейно зависимы


$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$

__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

__Решение__

In [6]:
B = np.matrix("0 0 10; 2 0 0; 0 1 0")
print(np.linalg.det(B))

20.000000000000007


Так как определитель отличен от нуля, то векторы образуют базис, следовательно, вектор можно разложить по данному базису

In [7]:
x = np.array([2, 3, 5])
print(np.linalg.solve(B.T, x))

[0.5 1.  3. ]


то есть координатами вектора $x$ в базисе $B$ являются $0.5,\: 1,\: 3$.

__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;

   б) в базисе $x^{2}$, $x-1$, $1$.

__Решение__

а) в базисе $1,\: x,\: x^{2}$;

По формуле Тейлора, любой многочлен степени не выше 3 можно представить в виде линейной комбинации линейно независимых векторов. Воспользуемся формулой Тейлора:
$f(x) = \sum_{n=0}^k \frac{f^{(n)}(a)}{n!}(x - a)^n=f(a)+ f'(a)(x - a) \\ + \frac{f^{(2)}(a)}{2!}(x - a)^2 + \ldots + \frac{f^{(k)}(a)}{k!}(x - a)^k$

$f(t) = f(0) + f'(0)(x - 0) + \frac{f^{(2)}(0)}{2!}(x - 0)^2$

Найдем производные для $f(x) = 3x^2 - 2 x + 2$:

$f'(x) = 6x -2, \\ f''(x) = 6$

Найдем коэффициенты-координаты:

$f(0) = 2;\\ f'(0) = -2;\\ \frac{f''(0)}{2!} = 3$

т.е. многочлен $f$ имеет координаты $2, -2, 3$ в базисе $1,\: x,\: x^{2}$

Проверка:

In [8]:
B = np.matrix("1 0 0; 0 1 0; 0 0 1")
print(np.linalg.det(B))

1.0


In [9]:
x = np.array([2, -2, 3])
print(np.linalg.solve(B.T, x))

[ 2. -2.  3.]


б) в базисе $x^{2},\: x-1,\: 1$.

Сделаем замену $t = x-1$

In [10]:
x, t = symbols("x t")
x = t + 1
eq = 3 * x**2 - 2 * x + 2
eq = expand(eq)
print(eq)

3*t**2 + 4*t + 3


In [11]:
# c t
B = np.matrix("1 2 1; 0 1 0; 0 0 1")
print(np.linalg.det(B))

1.0


In [12]:
x = np.array([3, 4, 3])
print(np.linalg.solve(B.T, x))

[ 3. -2.  0.]


Решим без замен:

In [13]:
# c x
B = np.matrix("1 0 0; 0 1 -1; 0 0 1")
print(np.linalg.det(B))

1.0


In [14]:
x = np.array([3, -2, 2])
print(np.linalg.solve(B.T, x))

[ 3. -2.  0.]


т.е. многочлен имеет координаты $3, -2, 0$ в базисе $x^{2},\: x-1,\: 1$

__5.__ Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

б) все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$.

__Решение__

In [15]:
x1, x2, y1, y2, x3, x4, y3, y4 = symbols("x1 x2 y1 y2 x3 x4 y3 y4")

x = np.array([0, x2, x3])
y = np.array([y1, 0, y3])

print(x + y)

[y1 x2 x3 + y3]


а)
Подмножество линейного пространства является подпространством, если оно замкнуто относительно операций сложения и умножения на числа. Сумма "нулевых" и "ненулевых" столбцов не является столбцом того же вида, т.е. операция сложения незамкнута и подпространство не изоморфно $u^{n-1}$

б) Да, множество всех линейных комбинаций $\{u_{1}, u_{2}, ..., u_{n}\}$ всегда образует подпространство