In [1]:
import numpy as np
import sympy as sp
from scipy import linalg

## Практическое задание

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [2]:
a_1a = np.matrix("1 -2; 3 -4")
b_1a = np.matrix("1; 7")

In [3]:
det = np.linalg.det(a_1a)
if det == 0:
    print("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
    s_0 = a_1a[:, 0]
    s_1 = a_1a[:, 1]

    a_1 = np.column_stack((b_1a, s_1))
    det_1 = np.linalg.det(a_1)
    a_2 = np.column_stack((s_0, b_1a))
    det_2 = np.linalg.det(a_2)

    x_1 = det_1 / det
    x_2 = det_2 / det

    print(f"Решение системы:\n x1 = {x_1:.1f}\n x2 = {x_2:.1f}")

Решение системы:
 x1 = 5.0
 x2 = 2.0


   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [4]:
a_1b = np.matrix("2 -1 5; 1 1 -3; 2 4 1")
b_1b = np.matrix("10; -2; 1")

In [5]:
det = np.linalg.det(a_1b)
if det == 0:
    print("Определитель матрицы равен нулю, система имеет бесконечно много решений")
else:
    s_0 = a_1b[:, 0]
    s_1 = a_1b[:, 1]
    s_2 = a_1b[:, 2]

    a_1 = np.column_stack((b_1b, s_1, s_2))
    det_1 = np.linalg.det(a_1)
    a_2 = np.column_stack((s_0, b_1b, s_2))
    det_2 = np.linalg.det(a_2)
    a_3 = np.column_stack((s_0, s_1, b_1b))
    det_3 = np.linalg.det(a_3)

    x_1 = det_1 / det
    x_2 = det_2 / det
    x_3 = det_3 / det

    print(f"Решение системы: x1 = {x_1:.1f}, x2 = {x_2:.1f}, x3 = {x_3:.1f}")

Решение системы: x1 = 2.0, x2 = -1.0, x3 = 1.0


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$


Матрица коэффициентов $A$ будет иметь вид

$\begin{pmatrix}
1 & 2 & 4 \\
2 & 9 & 12 \\
3 & 26 & 30
\end{pmatrix}$

Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$.

Матрица коэффициентов будет иметь вид

$\begin{pmatrix}
1 & 2 & 4 \\
0 & 5 & 4 \\
0 & 20 & 18
\end{pmatrix},$

а матрица $L$ —

$\begin{pmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & l_{32} & 1
\end{pmatrix}.$

Далее умножим вторую строку на $4$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $4$.

В итоге получим

$U=\begin{pmatrix}
1 & 2 & 4 \\
0 & 5 & 4 \\
0 & 0 & 2
\end{pmatrix},$

$L=\begin{pmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
3 & 4 & 1
\end{pmatrix}.$

In [6]:
U = sp.Matrix([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
L = sp.Matrix([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
L @ U

Matrix([
[1,  2,  4],
[2,  9, 12],
[3, 26, 30]])

Решим в scipy

In [7]:
A_2a = sp.Matrix([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = linalg.lu(A_2a)
for t, x in zip([P, L, U], ["P =\n", "L =\n", "U =\n"]):
    print(x, t)

P =
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L =
 [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]]
U =
 [[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]


б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица коэффициентов
$\begin{pmatrix}
1 & 1 & 2 & 4\\
2 & 5 & 8 & 9\\
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

Начнем прямой ход метода Гаусса. Для этого домножим $1$ строку на $2$ и вычтем ее из $2$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$.

Домножим $1$ строку на $3$ и вычтем ее из $3$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{31}$ значение $3$.

Домножим $1$ строку на $4$ и вычтем ее из $4$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{41}$ значение $4$.

Домножим $2$ строку на $5$ и вычтем ее из $3$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{32}$ значение $5$.

Домножим $2$ строку на $6$ и вычтем ее из $4$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{42}$ значение $6$.

Домножим $3$ строку на $7$ и вычтем ее из $4$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{43}$ значение $7$.

В итоге получим

$U=\left(\begin{matrix}
1 & 1 & 2 & 4 \\
0 & 3 & 4 & 1 \\
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{matrix}\right),$

$L=\left(\begin{matrix}
1 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 \\
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{matrix}\right)$

In [8]:
U = sp.Matrix([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
L = sp.Matrix([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
L @ U

Matrix([
[1,  1,  2,  4],
[2,  5,  8,  9],
[3, 18, 29, 18],
[4, 22, 53, 33]])

Решим в scipy

In [9]:
A_2b = sp.Matrix([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = linalg.lu(A_2b)
for t, x in zip([P, L, U], ["P =\n", "L =\n", "U =\n"]):
    print(x, t)

P =
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
L =
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75       -0.25        1.          0.        ]
 [ 0.25        0.75       -0.17073171  1.        ]]
U =
 [[  4.          22.          53.          33.        ]
 [  0.          -6.         -18.5         -7.5       ]
 [  0.           0.         -15.375       -8.625     ]
 [  0.           0.           0.          -0.09756098]]


__3.__ Решить систему линейных уравнений методом $LU$-разложения

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

Матрица коэффициентов $A$ будет иметь вид

$\begin{pmatrix}
2 & 1 & 3 \\
11 & 7 & 5 \\
9 & 8 & 4
\end{pmatrix}.$

Начнем прямой ход метода Гаусса. Для этого домножим $1$ строку на $11/2$ и вычтем ее из $2$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $11/2$.

Начнем прямой ход метода Гаусса. Для этого домножим $1$ строку на $9/2$ и вычтем ее из $3$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{31}$ значение $9/2$.

Начнем прямой ход метода Гаусса. Для этого домножим $2$ строку на $7/3$ и вычтем ее из $3$ уравнения. При этом запишем в матрицу $L$ на место элемента $l_{32}$ значение $7/3$.

В итоге получим

$U=\left(\begin{matrix}
2 & 1 & 3 \\
0 & \frac{3}{2} & \frac{-23}{2} \\
0 & 0 & \frac{52}{3}
\end{matrix}\right),$

$L=\left(\begin{matrix}
1 & 0 & 0 \\
\frac{11}{2} & 1 & 0 \\
\frac{9}{2} & \frac{7}{3} & 1
\end{matrix}\right)$

Решим теперь систему

$$Ly=b:$$

$\begin{cases}
y_{1}=1, \\
\frac{11}{2} y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+\frac{7}{3}y_{2}+y_{3}=-5.
\end{cases}$

$$y_{1}=1,$$
$$y_{2}=\frac{-23}{2},$$
$$y_{3}=\frac{52}{3}.$$

И затем систему

$$Ux=y:$$

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
\frac{3}{2}x_{2}-\frac{23}{2}x_{3}=\frac{-23}{2}, \\
\frac{52}{3}x_{3}=\frac{52}{3}.
\end{cases}$

$$x_{1}=-1,$$
$$x_{2}=0,$$
$$x_{3}=1.$$

Произведем проверку, подставив полученные значения переменных в исходную систему:

$\begin{cases}
2\cdot(-1)+1\cdot 0+3\cdot 1=1 \\
11\cdot(-1)+7\cdot 0+5\cdot 1=-6 \\
9\cdot(-1)+8\cdot 0+4\cdot 1=-5
\end{cases}$

Таким образом, найденное решение верно.


__4.__ Решить систему линейных уравнений методом Холецкого

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$
$$l_{22}=\sqrt{a_{22}-u_{21}^{2}}=\sqrt{50-(-5)^{2}}=\sqrt{25}=5,$$

$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{-15-5\cdot (-5)}{5}=2,$$

$$l_{33}=\sqrt{a_{33}-l_{13}^{2}-l_{23}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу

$L = \begin{pmatrix}
9 & 0 & 0 \\
-5 & 5 & 0 \\
5 & 2 & 3
\end{pmatrix},
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\
0 & 5 & 2 \\
0 & 0 & 3
\end{pmatrix}.$

Решим систему $Ly=b:$

$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$

$$y_{1} = 59,$$
$$y_{2}=-33,$$
$$y_{3}=-12.$$

И решим систему $L^{T}x=y:$

$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$

$$x_{1}=6,$$
$$x_{2}=-5,$$
$$x_{3}=-4.$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.


In [10]:
def cholesky(arr):
    n = len(arr)
    for k in range(n):
        try:
            arr[k, k] = (arr[k, k] - arr[k, 0:k] @ arr[k, 0:k]) ** 0.5
        except Exception as e:
            print(
                "Факторизация Холецкого предназначена только для симметричных положительно определенных матриц"
            )
        for i in range(k + 1, n):
            arr[i, k] = (arr[i, k] - arr[i, 0:k] @ arr[k, 0:k]) / arr[k, k]
    for k in range(1, n):
        arr[0:k, k] = 0.0
    return arr

In [11]:
arr = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
L = cholesky(arr)
L

array([[ 9,  0,  0],
       [-5,  5,  0],
       [ 5,  2,  3]])

In [12]:
# встроенные функции

A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
B = np.array([531, -460, 193])

L_matrix = np.linalg.cholesky(A)
Y_cf = linalg.solve_triangular(L_matrix, B, lower=True, check_finite=False)
X_cf = linalg.solve_triangular(L_matrix, Y_cf, lower=True, trans=1, check_finite=False)

In [13]:
L_matrix, Y_cf, X_cf

(array([[ 9.,  0.,  0.],
        [-5.,  5.,  0.],
        [ 5.,  2.,  3.]]),
 array([ 59., -33., -12.]),
 array([ 6., -5., -4.]))