__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение:__

Матрицу $A$ можно умножить не на всякую матрицу $B$: необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
Произведение матриц не удовлетворяет условию выше.

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

$AB$ - $2\times 3$, $BA$ - не удовлетворяет условию выше, нельзя перемножить

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

$AB$ - $8\times 8$, $BA$ - $3\times 3$

In [1]:
import numpy as np

A = np.ones((8, 3))
B = np.ones((3, 8))

(A @ B).shape  # в нашем случае можно и так
# np.dot(A, B).shape

(8, 8)

In [2]:
(B @ A).shape

(3, 3)

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

$AB$ - $4\times 4$, $BA$ - $4\times 4$

In [3]:
import numpy as np

A = np.ones((4, 4))
B = np.ones((4, 4))

(A @ B).shape
# np.dot(A, B).shape

(4, 4)

In [4]:
(B @ A).shape

(4, 4)

__2.__ Найти сумму и произведение матриц
$A=\begin{pmatrix}
1 & -2\\
3 & 0
\end{pmatrix}$ и
$B=\begin{pmatrix}
4 & -1\\
0 & 5
\end{pmatrix}.$

__Решение:__

In [5]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f"Сумма матриц, матрица: \n{A + B}")
print(f"Произведение матриц, матрица: \n{np.dot(A, B)}")

Сумма матриц, матрица: 
[[ 5 -3]
 [ 3  5]]
Произведение матриц, матрица: 
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix}.$

__Решение:__

$3\cdot \begin{pmatrix}
1 & 7\\
3 & -6
\end{pmatrix}-
2\cdot \begin{pmatrix}
0 & 5\\
2 & -1
\end{pmatrix}+
4\cdot \begin{pmatrix}
2 & -4\\
1 & 1
\end{pmatrix} =
\begin{pmatrix}
3 & 21\\
9 & -18
\end{pmatrix}-
\begin{pmatrix}
0 & 10\\
4 & -2
\end{pmatrix}+
\begin{pmatrix}
8 & -16\\
4 & 4
\end{pmatrix} =
\begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}$

__Ответ:__

$\begin{pmatrix}
11 & -5\\
9 & -12
\end{pmatrix}$

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

B2 = -2 * B

print(f"Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = \n{3 * A + B2 + 4 * C}\n")

Линейная комбинация  3𝐴 − 2𝐵 + 4𝐶 для матриц 𝐴 = 
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\
5 & -2\\
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


__Решение:__

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [8]:
A @ A.T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [9]:
A.T @ A

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

__Решение:__

In [10]:
def matmul(X, Y):
    result = [
        [sum(a * b for a, b in zip(X_row, Y_col)) for Y_col in zip(*Y)] for X_row in X
    ]
    print([i for i in result])

In [11]:
X = [[1, 2, 3, 2], [4, 5, 6, 5], [7, 8, 9, 8]]
Y = [[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]

matmul(X, Y)

[[22, 30, 38, 46, 54], [52, 72, 92, 112, 132], [82, 114, 146, 178, 210]]


__Проверка:__

In [12]:
np.array(X) @ np.array(Y)

array([[ 22,  30,  38,  46,  54],
       [ 52,  72,  92, 112, 132],
       [ 82, 114, 146, 178, 210]])