In [48]:
import numpy as np
import scipy.linalg as la

np.set_printoptions(precision=2, suppress=True)

## Практическое задание

1. Найдите посредством NumPy SVD для матрицы:

$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$

In [49]:
M = np.array(
    [
        [1, 2, 0],
        [0, 0, 5],
        [3, -4, 2],
        [1, 6, 5],
        [0, 1, 0],
    ]
)
print(M)

[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [50]:
u, s, v = np.linalg.svd(M, full_matrices=False)
for t, x in zip([u, s, v], ["U =\n", "S =\n", "V =\n"]):
    print(x, t)

U =
 [[ 0.17  0.16 -0.53]
 [ 0.39 -0.53  0.61]
 [-0.14 -0.82 -0.52]
 [ 0.89  0.06 -0.25]
 [ 0.08  0.11 -0.08]]
S =
 [8.82 6.14 2.53]
V =
 [[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]


In [51]:
D = np.diag(s)
print(D)

[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]]


Проверим полученный результат $U\cdot D\cdot V^T=A$

In [52]:
print("Product\n", u @ np.diag(s) @ v)

Product
 [[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найдите:

а) евклидову норму;
Для SVD разложения:
$\left \| A \right \|_{E}={max}(D)=\mu_{1}=D_{11}=8,8249$

In [53]:
print(np.linalg.norm(s[0]))
print(np.linalg.norm(M, ord=2))

8.824868854820444
8.824868854820444


б) норму Фробениуса.

$\left \| A \right \|_{F}=\sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}^{2}}==\sqrt{1^2+2^2+0^2+0^2+0^2+5^2+3^2+(-4)^2+2^2+1^2+6^2+5^2+0^2+1^2+0^2}=\sqrt{122}=11,045361$
$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}=\sqrt{8,8249^2+6,1406^2+2,5327^2}=11,045379$

In [54]:
print(np.linalg.norm(s))
print((np.sum(s**2)) ** 0.5)
la.norm(M, ord="fro")

11.045361017187263
11.045361017187263


11.045361017187261